# Generated by Django 3.1.2 on 2020-10-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_data',
            field=models.JSONField(default=dict),
        ),
    ]
